const mock = {
  generalesContratacion: {
    tipoProc: "C.A.",
    numProc: "224",
    anoProc: "2022",
    objProc: "Compra de cosas de limpieza",
    cantReng: 34,
    cantProv: 4,
    categoriaProc: "ELECTRICIDAD Y TELEFONIA",
    organismoProc: "HPMI",
    presupProc: 15000000,
  },
  detallesContratacion: [
    [
      1,
      1,
      "CABO DE MADERA GRUESO P/HARAGANES - CON ROSCA - DE 2 MTS.",
      50,
      null,
    ],
    [2, 2, "CEPILLO ARAÑERO DE CERDAS PLÁSTICAS", 5, null],
    [3, 3, "CEPILLO DE LAVAR ZAPATILLA (TIPO PLANCHA)", 25, null],
    [4, 4, "CEPILLO SANITARIO PARA BAÑO C/BASE", 10, null],
    [
      5,
      5,
      "SECADOR DE PISO DE GOMA DE 50 CM. CON ALMA DE ACERO (TIPO SACCHI)",
      90,
      null,
    ],
    [6, 6, "ESPONJA DE ACERO DE 50 GRS", 240, null],
    [
      7,
      7,
      "ESPONJA LAVAVAJILLA ANTIADHERENTE (ESPUMA CUBIERTA DE RED PLÁSTICA)",
      160,
      "Desierto",
    ],
    [
      8,
      8,
      "ESPONJA LAVAVAJILLAS AMARILLA C/FIBRA SUPERIOR - T/MORTIMER 10 X 5 APROX.",
      200,
      null,
    ],
    [
      9,
      9,
      "FRANELA NARANJA 45 X 60 CM. PURO ALGODÓN TRIPLE FRI- SADO",
      300,
      null,
    ],
    [
      10,
      10,
      "LANA DE ACERO TIPO VIRULANA X 10 UNIDADES X 70 GRAMOS APROX.",
      100,
      null,
    ],
    [
      11,
      11,
      "PAÑO ABSORBENTE AMARILLO DE 38 X 38 CM (TIPO VALERINA)",
      300,
      null,
    ],
    [
      12,
      12,
      "PAÑO DE LIMPIEZA DESCARTABLE CON AGENTE ANTI BACTERIAS X ROLLO DE 60 U. DE 30X30CM. NO DEJA PELUSA. (TIPO SUPER PRO BETTANIN )",
      200,
      null,
    ],
    [
      13,
      13,
      "REJILLA DE ALGODÓON TRAMA CERRADA - 42 X 58 CM (LAVA- COCHES)",
      300,
      null,
    ],
    [
      14,
      14,
      "TRAPO DE PISO - COLOR GRIS - MED. 60 X 70 - (T/MEDIA NA- RANJA)",
      200,
      null,
    ],
    [15, 15, "JABÓN EN PAN X 150 O MÁS GRS TIPO OCRE", 30, null],
    [16, 16, "JABÓN EN PAN BLANCO X 250 GRS.", 30, null],
    [17, 17, "JABÓN EN POLVO X 800 G BAJA ESPUMA", 20, null],
    [
      18,
      18,
      'INSECTICIDA EN AEROSOL "MATA MOSCAS Y MOSQUITOS" X 360 CC',
      48,
      null,
    ],
    [19, 19, "BOLSA DE CONSORCIO - 80 CM X 110 CM - 50 MICRONES", 16000, null],
    [20, 20, "BOLSA DE CONSORCIO - 45 CM X 60CM - 30 MICRONES", 56000, null],
    [
      21,
      21,
      "BOLSA LEBRILLO ROJA SIN FUELLE - 60 CM X 55 CM - 50 MI- CRONES",
      6000,
      null,
    ],
    [
      22,
      22,
      "BOLSA DE CONSORCIO ROJA - 60 CM X 120 CM - 50 MICRONES",
      3000,
      null,
    ],
    [
      23,
      23,
      "BOLSA DE CONSORCIO ROJA - 80 CM X 100 CM - 55 MICRONES",
      3000,
      null,
    ],
    [24, 24, "BOLSA DE CONSORCIO - 50 CM X 70 CM - 50 MICRONES", 14000, null],
    [25, 25, "BOLSA DE CONSORCIO - 60 CM X 120 CM - 50 MICRONES", 7000, null],
    [
      26,
      26,
      "BOLSA DE CONSORCIO ROJA - 50 CM X 60 CM - 30 MICRONES",
      56000,
      null,
    ],
    [
      27,
      27,
      "BOLSA DE CONSORCIO VERDE PARA ROPA SIN FUELLE - 50 CM X 70 CM - 30 MICRONES",
      1500,
      null,
    ],
    [28, 28, "BOLSA CELESTE 80 CM X 100 CM", 1500, null],
    [
      29,
      29,
      "TOALLAS INTERCALADAS X 10 PAQ. X 250 c/u - COLOR BLANCO DE 4 PANELES - MEDIDAS: 19 CM X 24 CM",
      600,
      null,
    ],
    [30, 30, "PAPEL SULFITO BALA X 10 KGS", 2, null],
    [31, 31, "PULVERIZADOR CON GATILLO - POR 1 LT. - PLÁSTICO", 60, null],
    [32, 32, "FÓSFOROS X 200 UNIDADES", 20, null],
    [33, 33, "PRECINTOS PLÁSTICOS X 15 CM", 4000, null],
    [34, 34, "PRECINTOS PLÁSTICOS X 40 CM", 600, null],
  ],
  ofertasRecibidas: {
    1: {
      1: {
        prov: "SERVICIOS HIGIENICOS DEL NOA",
        nProv: 3,
        nOrden: 1,
        nReng: 1,
        nAlt: 0,
        qOfert: 50,
        pUnit: 319,
        observacion: "",
        numProv: 0,
      },
      2: {
        prov: "OLMOS CARLOS (DIOL)",
        nProv: 2,
        nOrden: 1,
        nReng: 1,
        nAlt: 0,
        qOfert: 50,
        pUnit: 398.4651,
        observacion: "",
        numProv: 0,
      },
      3: {
        prov: "PEREZ SIROMBRA FRANCISCO",
        nProv: 1,
        nOrden: 1,
        nReng: 1,
        nAlt: 0,
        qOfert: 5,
        pUnit: 517,
        observacion: "",
        numProv: 0,
      },
      4: {
        prov: "RODRIGUEZ BOSCHERO ESTEBAN",
        nProv: 4,
        nOrden: 1,
        nReng: 1,
        nAlt: 0,
        qOfert: 50,
        pUnit: 846.59,
        observacion: "",
        numProv: 0,
      },
    },
    2: {
      1: {
        prov: "SERVICIOS HIGIENICOS DEL NOA",
        nProv: 3,
        nOrden: 2,
        nReng: 2,
        nAlt: 0,
        qOfert: 5,
        pUnit: 398,
        observacion: "",
        numProv: 0,
      },
      2: {
        prov: "PEREZ SIROMBRA FRANCISCO",
        nProv: 1,
        nOrden: 2,
        nReng: 2,
        nAlt: 0,
        qOfert: 5,
        pUnit: 457,
        observacion: "",
        numProv: 0,
      },
      3: {
        prov: "OLMOS CARLOS (DIOL)",
        nProv: 2,
        nOrden: 2,
        nReng: 2,
        nAlt: 0,
        qOfert: 5,
        pUnit: 591.206,
        observacion: "",
        numProv: 0,
      },
      4: {
        prov: "RODRIGUEZ BOSCHERO ESTEBAN",
        nProv: 4,
        nOrden: 2,
        nReng: 2,
        nAlt: 0,
        qOfert: 5,
        pUnit: 781.47,
        observacion: "",
        numProv: 0,
      },
    },
    3: {
      1: {
        prov: "SERVICIOS HIGIENICOS DEL NOA",
        nProv: 3,
        nOrden: 3,
        nReng: 3,
        nAlt: 0,
        qOfert: 25,
        pUnit: 247,
        observacion: "",
        numProv: 0,
      },
      2: {
        prov: "PEREZ SIROMBRA FRANCISCO",
        nProv: 1,
        nOrden: 3,
        nReng: 3,
        nAlt: 0,
        qOfert: 25,
        pUnit: 347,
        observacion: "",
        numProv: 0,
      },
      3: {
        prov: "OLMOS CARLOS (DIOL)",
        nProv: 2,
        nOrden: 3,
        nReng: 3,
        nAlt: 0,
        qOfert: 25,
        pUnit: 447.095,
        observacion: "",
        numProv: 0,
      },
      4: {
        prov: "RODRIGUEZ BOSCHERO ESTEBAN",
        nProv: 4,
        nOrden: 3,
        nReng: 3,
        nAlt: 0,
        qOfert: 25,
        pUnit: 738.05,
        observacion: "",
        numProv: 0,
      },
    },
    4: {
      1: {
        prov: "SERVICIOS HIGIENICOS DEL NOA",
        nProv: 3,
        nOrden: 4,
        nReng: 4,
        nAlt: 0,
        qOfert: 10,
        pUnit: 485,
        observacion: "",
        numProv: 0,
      },
      2: {
        prov: "PEREZ SIROMBRA FRANCISCO",
        nProv: 1,
        nOrden: 4,
        nReng: 4,
        nAlt: 0,
        qOfert: 10,
        pUnit: 517,
        observacion: "",
        numProv: 0,
      },
      3: {
        prov: "OLMOS CARLOS (DIOL)",
        nProv: 2,
        nOrden: 4,
        nReng: 4,
        nAlt: 0,
        qOfert: 10,
        pUnit: 654.489,
        observacion: "",
        numProv: 0,
      },
      4: {
        prov: "RODRIGUEZ BOSCHERO ESTEBAN",
        nProv: 4,
        nOrden: 4,
        nReng: 4,
        nAlt: 0,
        qOfert: 10,
        pUnit: 1085.37,
        observacion: "",
        numProv: 0,
      },
    },
    5: {
      1: {
        prov: "PEREZ SIROMBRA FRANCISCO",
        nProv: 1,
        nOrden: 5,
        nReng: 5,
        nAlt: 0,
        qOfert: 90,
        pUnit: 457,
        observacion: "",
        numProv: 0,
      },
      2: {
        prov: "OLMOS CARLOS (DIOL)",
        nProv: 2,
        nOrden: 5,
        nReng: 5,
        nAlt: 0,
        qOfert: 90,
        pUnit: 744.5614,
        observacion: "",
        numProv: 0,
      },
      3: {
        prov: "SERVICIOS HIGIENICOS DEL NOA",
        nProv: 3,
        nOrden: 5,
        nReng: 5,
        nAlt: 0,
        qOfert: 90,
        pUnit: 1230,
        observacion: "",
        numProv: 0,
      },
      4: {
        prov: "RODRIGUEZ BOSCHERO ESTEBAN",
        nProv: 4,
        nOrden: 5,
        nReng: 5,
        nAlt: 0,
        qOfert: 90,
        pUnit: 2170.74,
        observacion: "",
        numProv: 0,
      },
    },
    6: {
      1: {
        prov: "OLMOS CARLOS (DIOL)",
        nProv: 2,
        nOrden: 6,
        nReng: 6,
        nAlt: 0,
        qOfert: 240,
        pUnit: 98.3246,
        observacion: "",
        numProv: 0,
      },
      2: {
        prov: "SERVICIOS HIGIENICOS DEL NOA",
        nProv: 3,
        nOrden: 6,
        nReng: 6,
        nAlt: 0,
        qOfert: 240,
        pUnit: 182.3,
        observacion: "",
        numProv: 0,
      },
      3: {
        prov: "PEREZ SIROMBRA FRANCISCO",
        nProv: 1,
        nOrden: 6,
        nReng: 6,
        nAlt: 0,
        qOfert: 240,
        pUnit: 237,
        observacion: "",
        numProv: 0,
      },
      4: {
        prov: "RODRIGUEZ BOSCHERO ESTEBAN",
        nProv: 4,
        nOrden: 6,
        nReng: 6,
        nAlt: 0,
        qOfert: 300,
        pUnit: 390.73,
        observacion: "",
        numProv: 0,
      },
    },
    8: {
      1: {
        prov: "SERVICIOS HIGIENICOS DEL NOA",
        nProv: 3,
        nOrden: 8,
        nReng: 8,
        nAlt: 0,
        qOfert: 200,
        pUnit: 40.9,
        observacion: "",
        numProv: 0,
      },
      2: {
        prov: "OLMOS CARLOS (DIOL)",
        nProv: 2,
        nOrden: 8,
        nReng: 8,
        nAlt: 0,
        qOfert: 200,
        pUnit: 69.4056,
        observacion: "",
        numProv: 0,
      },
      3: {
        prov: "PEREZ SIROMBRA FRANCISCO",
        nProv: 1,
        nOrden: 8,
        nReng: 8,
        nAlt: 0,
        qOfert: 200,
        pUnit: 77,
        observacion: "",
        numProv: 0,
      },
      4: {
        prov: "RODRIGUEZ BOSCHERO ESTEBAN",
        nProv: 4,
        nOrden: 8,
        nReng: 8,
        nAlt: 0,
        qOfert: 200,
        pUnit: 162.81,
        observacion: "",
        numProv: 0,
      },
    },
    9: {
      1: {
        prov: "SERVICIOS HIGIENICOS DEL NOA",
        nProv: 3,
        nOrden: 9,
        nReng: 9,
        nAlt: 0,
        qOfert: 300,
        pUnit: 209,
        observacion: "",
        numProv: 0,
      },
      2: {
        prov: "OLMOS CARLOS (DIOL)",
        nProv: 2,
        nOrden: 9,
        nReng: 9,
        nAlt: 0,
        qOfert: 300,
        pUnit: 241.2135,
        observacion: "",
        numProv: 0,
      },
      3: {
        prov: "PEREZ SIROMBRA FRANCISCO",
        nProv: 1,
        nOrden: 9,
        nReng: 9,
        nAlt: 0,
        qOfert: 300,
        pUnit: 297,
        observacion: "",
        numProv: 0,
      },
      4: {
        prov: "RODRIGUEZ BOSCHERO ESTEBAN",
        nProv: 4,
        nOrden: 9,
        nReng: 9,
        nAlt: 0,
        qOfert: 600,
        pUnit: 651.22,
        observacion: "",
        numProv: 0,
      },
    },
    10: {
      1: {
        prov: "SERVICIOS HIGIENICOS DEL NOA",
        nProv: 3,
        nOrden: 10,
        nReng: 10,
        nAlt: 0,
        qOfert: 100,
        pUnit: 109.15,
        observacion: "",
        numProv: 0,
      },
      2: {
        prov: "PEREZ SIROMBRA FRANCISCO",
        nProv: 1,
        nOrden: 10,
        nReng: 10,
        nAlt: 0,
        qOfert: 100,
        pUnit: 117,
        observacion: "",
        numProv: 0,
      },
      3: {
        prov: "OLMOS CARLOS (DIOL)",
        nProv: 2,
        nOrden: 10,
        nReng: 10,
        nAlt: 0,
        qOfert: 100,
        pUnit: 142.7074,
        observacion: "",
        numProv: 0,
      },
      4: {
        prov: "RODRIGUEZ BOSCHERO ESTEBAN",
        nProv: 4,
        nOrden: 10,
        nReng: 10,
        nAlt: 0,
        qOfert: 100,
        pUnit: 238.78,
        observacion: "",
        numProv: 0,
      },
    },
    11: {
      1: {
        prov: "SERVICIOS HIGIENICOS DEL NOA",
        nProv: 3,
        nOrden: 11,
        nReng: 11,
        nAlt: 0,
        qOfert: 300,
        pUnit: 50.5,
        observacion: "",
        numProv: 0,
      },
      2: {
        prov: "OLMOS CARLOS (DIOL)",
        nProv: 2,
        nOrden: 11,
        nReng: 11,
        nAlt: 0,
        qOfert: 300,
        pUnit: 68.4618,
        observacion: "",
        numProv: 0,
      },
      3: {
        prov: "PEREZ SIROMBRA FRANCISCO",
        nProv: 1,
        nOrden: 11,
        nReng: 11,
        nAlt: 0,
        qOfert: 300,
        pUnit: 117,
        observacion: "",
        numProv: 0,
      },
      4: {
        prov: "RODRIGUEZ BOSCHERO ESTEBAN",
        nProv: 4,
        nOrden: 11,
        nReng: 11,
        nAlt: 0,
        qOfert: 300,
        pUnit: 311.14,
        observacion: "",
        numProv: 0,
      },
    },
    12: {
      1: {
        prov: "SERVICIOS HIGIENICOS DEL NOA",
        nProv: 3,
        nOrden: 12,
        nReng: 12,
        nAlt: 0,
        qOfert: 200,
        pUnit: 217,
        observacion: "",
        numProv: 0,
      },
      2: {
        prov: "RODRIGUEZ BOSCHERO ESTEBAN",
        nProv: 4,
        nOrden: 12,
        nReng: 12,
        nAlt: 0,
        qOfert: 200,
        pUnit: 2170.74,
        observacion: "",
        numProv: 0,
      },
      3: {
        prov: "OLMOS CARLOS (DIOL)",
        nProv: 2,
        nOrden: 12,
        nReng: 12,
        nAlt: 0,
        qOfert: 200,
        pUnit: 3624.8091,
        observacion: "",
        numProv: 0,
      },
      4: {
        prov: "PEREZ SIROMBRA FRANCISCO",
        nProv: 1,
        nOrden: 12,
        nReng: 12,
        nAlt: 0,
        qOfert: 200,
        pUnit: 5697,
        observacion: "",
        numProv: 0,
      },
    },
    13: {
      1: {
        prov: "SERVICIOS HIGIENICOS DEL NOA Alt. 1",
        nProv: 3,
        nOrden: 13,
        nReng: 13,
        nAlt: 1,
        qOfert: 300,
        pUnit: 98,
        observacion: "",
        numProv: 0,
      },
      2: {
        prov: "SERVICIOS HIGIENICOS DEL NOA",
        nProv: 3,
        nOrden: 13,
        nReng: 13,
        nAlt: 0,
        qOfert: 300,
        pUnit: 174,
        observacion: "",
        numProv: 0,
      },
      3: {
        prov: "SERVICIOS HIGIENICOS DEL NOA Alt. 2",
        nProv: 3,
        nOrden: 13,
        nReng: 13,
        nAlt: 2,
        qOfert: 300,
        pUnit: 290,
        observacion: "",
        numProv: 0,
      },
      4: {
        prov: "OLMOS CARLOS (DIOL)",
        nProv: 2,
        nOrden: 13,
        nReng: 13,
        nAlt: 0,
        qOfert: 300,
        pUnit: 339.1751,
        observacion: "",
        numProv: 0,
      },
      5: {
        prov: "PEREZ SIROMBRA FRANCISCO",
        nProv: 1,
        nOrden: 13,
        nReng: 13,
        nAlt: 0,
        qOfert: 300,
        pUnit: 467,
        observacion: "",
        numProv: 0,
      },
      6: {
        prov: "RODRIGUEZ BOSCHERO ESTEBAN",
        nProv: 4,
        nOrden: 13,
        nReng: 13,
        nAlt: 0,
        qOfert: 300,
        pUnit: 672.93,
        observacion: "",
        numProv: 0,
      },
    },
    14: {
      1: {
        prov: "SERVICIOS HIGIENICOS DEL NOA Alt. 1",
        nProv: 3,
        nOrden: 14,
        nReng: 14,
        nAlt: 1,
        qOfert: 200,
        pUnit: 54.5,
        observacion: "",
        numProv: 0,
      },
      2: {
        prov: "SERVICIOS HIGIENICOS DEL NOA",
        nProv: 3,
        nOrden: 14,
        nReng: 14,
        nAlt: 0,
        qOfert: 200,
        pUnit: 245,
        observacion: "",
        numProv: 0,
      },
      3: {
        prov: "PEREZ SIROMBRA FRANCISCO",
        nProv: 1,
        nOrden: 14,
        nReng: 14,
        nAlt: 0,
        qOfert: 200,
        pUnit: 247,
        observacion: "",
        numProv: 0,
      },
      4: {
        prov: "OLMOS CARLOS (DIOL)",
        nProv: 2,
        nOrden: 14,
        nReng: 14,
        nAlt: 0,
        qOfert: 200,
        pUnit: 377.2054,
        observacion: "",
        numProv: 0,
      },
      5: {
        prov: "RODRIGUEZ BOSCHERO ESTEBAN",
        nProv: 4,
        nOrden: 14,
        nReng: 14,
        nAlt: 0,
        qOfert: 200,
        pUnit: 520.98,
        observacion: "",
        numProv: 0,
      },
    },
    15: {
      1: {
        prov: "OLMOS CARLOS (DIOL)",
        nProv: 2,
        nOrden: 15,
        nReng: 15,
        nAlt: 0,
        qOfert: 30,
        pUnit: 61.0082,
        observacion: "",
        numProv: 0,
      },
      2: {
        prov: "SERVICIOS HIGIENICOS DEL NOA",
        nProv: 3,
        nOrden: 15,
        nReng: 15,
        nAlt: 0,
        qOfert: 30,
        pUnit: 106.65,
        observacion: "",
        numProv: 0,
      },
      3: {
        prov: "PEREZ SIROMBRA FRANCISCO",
        nProv: 1,
        nOrden: 15,
        nReng: 15,
        nAlt: 0,
        qOfert: 30,
        pUnit: 117,
        observacion: "",
        numProv: 0,
      },
      4: {
        prov: "RODRIGUEZ BOSCHERO ESTEBAN",
        nProv: 4,
        nOrden: 15,
        nReng: 15,
        nAlt: 0,
        qOfert: 30,
        pUnit: 217.07,
        observacion: "",
        numProv: 0,
      },
    },
    16: {
      1: {
        prov: "PEREZ SIROMBRA FRANCISCO",
        nProv: 1,
        nOrden: 16,
        nReng: 16,
        nAlt: 0,
        qOfert: 30,
        pUnit: 117,
        observacion: "",
        numProv: 0,
      },
      2: {
        prov: "OLMOS CARLOS (DIOL)",
        nProv: 2,
        nOrden: 16,
        nReng: 16,
        nAlt: 0,
        qOfert: 30,
        pUnit: 133.0879,
        observacion: "",
        numProv: 0,
      },
      3: {
        prov: "RODRIGUEZ BOSCHERO ESTEBAN",
        nProv: 4,
        nOrden: 16,
        nReng: 16,
        nAlt: 0,
        qOfert: 30,
        pUnit: 260.49,
        observacion: "",
        numProv: 0,
      },
    },
    17: {
      1: {
        prov: "OLMOS CARLOS (DIOL)",
        nProv: 2,
        nOrden: 17,
        nReng: 17,
        nAlt: 0,
        qOfert: 20,
        pUnit: 398.6224,
        observacion: "",
        numProv: 0,
      },
      2: {
        prov: "SERVICIOS HIGIENICOS DEL NOA",
        nProv: 3,
        nOrden: 17,
        nReng: 17,
        nAlt: 0,
        qOfert: 20,
        pUnit: 565,
        observacion: "",
        numProv: 0,
      },
      3: {
        prov: "PEREZ SIROMBRA FRANCISCO",
        nProv: 1,
        nOrden: 17,
        nReng: 17,
        nAlt: 0,
        qOfert: 20,
        pUnit: 2337,
        observacion: "",
        numProv: 0,
      },
    },
    18: {
      1: {
        prov: "SERVICIOS HIGIENICOS DEL NOA",
        nProv: 3,
        nOrden: 18,
        nReng: 18,
        nAlt: 0,
        qOfert: 48,
        pUnit: 355.2,
        observacion: "",
        numProv: 0,
      },
      2: {
        prov: "PEREZ SIROMBRA FRANCISCO",
        nProv: 1,
        nOrden: 18,
        nReng: 18,
        nAlt: 0,
        qOfert: 48,
        pUnit: 387,
        observacion: "",
        numProv: 0,
      },
      3: {
        prov: "OLMOS CARLOS (DIOL)",
        nProv: 2,
        nOrden: 18,
        nReng: 18,
        nAlt: 0,
        qOfert: 48,
        pUnit: 594.8118,
        observacion: "",
        numProv: 0,
      },
      4: {
        prov: "RODRIGUEZ BOSCHERO ESTEBAN",
        nProv: 4,
        nOrden: 18,
        nReng: 18,
        nAlt: 0,
        qOfert: 48,
        pUnit: 1020.25,
        observacion: "",
        numProv: 0,
      },
    },
    19: {
      1: {
        prov: "SERVICIOS HIGIENICOS DEL NOA",
        nProv: 3,
        nOrden: 19,
        nReng: 19,
        nAlt: 0,
        qOfert: 16000,
        pUnit: 44,
        observacion: "",
        numProv: 0,
      },
      2: {
        prov: "PEREZ SIROMBRA FRANCISCO",
        nProv: 1,
        nOrden: 19,
        nReng: 19,
        nAlt: 0,
        qOfert: 16000,
        pUnit: 56.7,
        observacion: "",
        numProv: 0,
      },
      3: {
        prov: "RODRIGUEZ BOSCHERO ESTEBAN",
        nProv: 4,
        nOrden: 19,
        nReng: 19,
        nAlt: 0,
        qOfert: 16000,
        pUnit: 130.24,
        observacion: "",
        numProv: 0,
      },
    },
    20: {
      1: {
        prov: "PEREZ SIROMBRA FRANCISCO",
        nProv: 1,
        nOrden: 20,
        nReng: 20,
        nAlt: 0,
        qOfert: 56000,
        pUnit: 6.7,
        observacion: "",
        numProv: 0,
      },
      2: {
        prov: "SERVICIOS HIGIENICOS DEL NOA",
        nProv: 3,
        nOrden: 20,
        nReng: 20,
        nAlt: 0,
        qOfert: 56000,
        pUnit: 9.3,
        observacion: "",
        numProv: 0,
      },
      3: {
        prov: "RODRIGUEZ BOSCHERO ESTEBAN",
        nProv: 4,
        nOrden: 20,
        nReng: 20,
        nAlt: 0,
        qOfert: 56000,
        pUnit: 48.62,
        observacion: "",
        numProv: 0,
      },
    },
    21: {
      1: {
        prov: "SERVICIOS HIGIENICOS DEL NOA",
        nProv: 3,
        nOrden: 21,
        nReng: 21,
        nAlt: 0,
        qOfert: 6000,
        pUnit: 22.2,
        observacion: "",
        numProv: 0,
      },
    },
    22: {
      1: {
        prov: "SERVICIOS HIGIENICOS DEL NOA",
        nProv: 3,
        nOrden: 22,
        nReng: 22,
        nAlt: 0,
        qOfert: 3000,
        pUnit: 48,
        observacion: "",
        numProv: 0,
      },
      2: {
        prov: "RODRIGUEZ BOSCHERO ESTEBAN",
        nProv: 4,
        nOrden: 22,
        nReng: 22,
        nAlt: 0,
        qOfert: 3000,
        pUnit: 195.37,
        observacion: "",
        numProv: 0,
      },
    },
    23: {
      1: {
        prov: "SERVICIOS HIGIENICOS DEL NOA",
        nProv: 3,
        nOrden: 23,
        nReng: 23,
        nAlt: 0,
        qOfert: 3000,
        pUnit: 56.5,
        observacion: "",
        numProv: 0,
      },
      2: {
        prov: "RODRIGUEZ BOSCHERO ESTEBAN",
        nProv: 4,
        nOrden: 23,
        nReng: 23,
        nAlt: 0,
        qOfert: 3000,
        pUnit: 130.24,
        observacion: "",
        numProv: 0,
      },
    },
    24: {
      1: {
        prov: "SERVICIOS HIGIENICOS DEL NOA",
        nProv: 3,
        nOrden: 24,
        nReng: 24,
        nAlt: 0,
        qOfert: 14000,
        pUnit: 18.6,
        observacion: "",
        numProv: 0,
      },
      2: {
        prov: "PEREZ SIROMBRA FRANCISCO",
        nProv: 1,
        nOrden: 24,
        nReng: 24,
        nAlt: 0,
        qOfert: 14000,
        pUnit: 19.7,
        observacion: "",
        numProv: 0,
      },
      3: {
        prov: "RODRIGUEZ BOSCHERO ESTEBAN",
        nProv: 4,
        nOrden: 24,
        nReng: 24,
        nAlt: 0,
        qOfert: 14000,
        pUnit: 108.54,
        observacion: "",
        numProv: 0,
      },
    },
    25: {
      1: {
        prov: "SERVICIOS HIGIENICOS DEL NOA",
        nProv: 3,
        nOrden: 25,
        nReng: 25,
        nAlt: 0,
        qOfert: 7000,
        pUnit: 38.25,
        observacion: "",
        numProv: 0,
      },
      2: {
        prov: "PEREZ SIROMBRA FRANCISCO",
        nProv: 1,
        nOrden: 25,
        nReng: 25,
        nAlt: 0,
        qOfert: 7000,
        pUnit: 39.7,
        observacion: "",
        numProv: 0,
      },
      3: {
        prov: "RODRIGUEZ BOSCHERO ESTEBAN",
        nProv: 4,
        nOrden: 25,
        nReng: 25,
        nAlt: 0,
        qOfert: 7000,
        pUnit: 260.49,
        observacion: "",
        numProv: 0,
      },
    },
    26: {
      1: {
        prov: "SERVICIOS HIGIENICOS DEL NOA",
        nProv: 3,
        nOrden: 26,
        nReng: 26,
        nAlt: 0,
        qOfert: 56000,
        pUnit: 13.5,
        observacion: "",
        numProv: 0,
      },
    },
    27: {
      1: {
        prov: "SERVICIOS HIGIENICOS DEL NOA",
        nProv: 3,
        nOrden: 27,
        nReng: 27,
        nAlt: 0,
        qOfert: 1500,
        pUnit: 13.57,
        observacion: "",
        numProv: 0,
      },
      2: {
        prov: "RODRIGUEZ BOSCHERO ESTEBAN",
        nProv: 4,
        nOrden: 27,
        nReng: 27,
        nAlt: 0,
        qOfert: 1500,
        pUnit: 60.78,
        observacion: "",
        numProv: 0,
      },
    },
    28: {
      1: {
        prov: "SERVICIOS HIGIENICOS DEL NOA",
        nProv: 3,
        nOrden: 28,
        nReng: 28,
        nAlt: 0,
        qOfert: 1500,
        pUnit: 53.4,
        observacion: "",
        numProv: 0,
      },
      2: {
        prov: "RODRIGUEZ BOSCHERO ESTEBAN",
        nProv: 4,
        nOrden: 28,
        nReng: 28,
        nAlt: 0,
        qOfert: 1500,
        pUnit: 82.49,
        observacion: "",
        numProv: 0,
      },
    },
    29: {
      1: {
        prov: "SERVICIOS HIGIENICOS DEL NOA",
        nProv: 3,
        nOrden: 29,
        nReng: 29,
        nAlt: 0,
        qOfert: 600,
        pUnit: 3200,
        observacion: "",
        numProv: 0,
      },
      2: {
        prov: "PEREZ SIROMBRA FRANCISCO",
        nProv: 1,
        nOrden: 29,
        nReng: 29,
        nAlt: 0,
        qOfert: 600,
        pUnit: 4227,
        observacion: "",
        numProv: 0,
      },
      3: {
        prov: "OLMOS CARLOS (DIOL)",
        nProv: 2,
        nOrden: 29,
        nReng: 29,
        nAlt: 0,
        qOfert: 600,
        pUnit: 4345.4246,
        observacion: "",
        numProv: 0,
      },
      4: {
        prov: "RODRIGUEZ BOSCHERO ESTEBAN",
        nProv: 4,
        nOrden: 29,
        nReng: 29,
        nAlt: 0,
        qOfert: 600,
        pUnit: 8248.81,
        observacion: "",
        numProv: 0,
      },
    },
    30: {
      1: {
        prov: "OLMOS CARLOS (DIOL)",
        nProv: 2,
        nOrden: 30,
        nReng: 30,
        nAlt: 0,
        qOfert: 2,
        pUnit: 4342.8473,
        observacion: "",
        numProv: 0,
      },
      2: {
        prov: "SERVICIOS HIGIENICOS DEL NOA",
        nProv: 3,
        nOrden: 30,
        nReng: 30,
        nAlt: 0,
        qOfert: 2,
        pUnit: 4480,
        observacion: "",
        numProv: 0,
      },
    },
    31: {
      1: {
        prov: "SERVICIOS HIGIENICOS DEL NOA",
        nProv: 3,
        nOrden: 31,
        nReng: 31,
        nAlt: 0,
        qOfert: 60,
        pUnit: 296.5,
        observacion: "",
        numProv: 0,
      },
      2: {
        prov: "PEREZ SIROMBRA FRANCISCO",
        nProv: 1,
        nOrden: 31,
        nReng: 31,
        nAlt: 0,
        qOfert: 60,
        pUnit: 397,
        observacion: "",
        numProv: 0,
      },
      3: {
        prov: "RODRIGUEZ BOSCHERO ESTEBAN",
        nProv: 4,
        nOrden: 31,
        nReng: 31,
        nAlt: 0,
        qOfert: 60,
        pUnit: 629.51,
        observacion: "",
        numProv: 0,
      },
      4: {
        prov: "OLMOS CARLOS (DIOL)",
        nProv: 2,
        nOrden: 31,
        nReng: 31,
        nAlt: 0,
        qOfert: 60,
        pUnit: 650.1693,
        observacion: "",
        numProv: 0,
      },
    },
    32: {
      1: {
        prov: "OLMOS CARLOS (DIOL)",
        nProv: 2,
        nOrden: 32,
        nReng: 32,
        nAlt: 0,
        qOfert: 20,
        pUnit: 116.6198,
        observacion: "",
        numProv: 0,
      },
      2: {
        prov: "SERVICIOS HIGIENICOS DEL NOA",
        nProv: 3,
        nOrden: 32,
        nReng: 32,
        nAlt: 0,
        qOfert: 20,
        pUnit: 125,
        observacion: "",
        numProv: 0,
      },
      3: {
        prov: "RODRIGUEZ BOSCHERO ESTEBAN",
        nProv: 4,
        nOrden: 32,
        nReng: 32,
        nAlt: 0,
        qOfert: 20,
        pUnit: 260.49,
        observacion: "",
        numProv: 0,
      },
    },
    33: {
      1: {
        prov: "SERVICIOS HIGIENICOS DEL NOA",
        nProv: 3,
        nOrden: 33,
        nReng: 33,
        nAlt: 0,
        qOfert: 4000,
        pUnit: 5.5,
        observacion: "",
        numProv: 0,
      },
      2: {
        prov: "PEREZ SIROMBRA FRANCISCO",
        nProv: 1,
        nOrden: 33,
        nReng: 33,
        nAlt: 0,
        qOfert: 4000,
        pUnit: 8.9,
        observacion: "",
        numProv: 0,
      },
      3: {
        prov: "RODRIGUEZ BOSCHERO ESTEBAN",
        nProv: 4,
        nOrden: 33,
        nReng: 33,
        nAlt: 0,
        qOfert: 4000,
        pUnit: 47.76,
        observacion: "",
        numProv: 0,
      },
    },
    34: {
      1: {
        prov: "SERVICIOS HIGIENICOS DEL NOA",
        nProv: 3,
        nOrden: 34,
        nReng: 34,
        nAlt: 0,
        qOfert: 600,
        pUnit: 14.5,
        observacion: "",
        numProv: 0,
      },
      2: {
        prov: "PEREZ SIROMBRA FRANCISCO",
        nProv: 1,
        nOrden: 34,
        nReng: 34,
        nAlt: 0,
        qOfert: 600,
        pUnit: 16.9,
        observacion: "",
        numProv: 0,
      },
      3: {
        prov: "RODRIGUEZ BOSCHERO ESTEBAN",
        nProv: 4,
        nOrden: 34,
        nReng: 34,
        nAlt: 0,
        qOfert: 600,
        pUnit: 108.54,
        observacion: "",
        numProv: 0,
      },
    },
  },
  condicionesOfertas: {
    1: {
      formaEntrega: "Según Pliego",
      formaPago: "Según Pliego",
      mantenimientoOferta: "Según Pliego",
      nombreProveedor: "PEREZ SIROMBRA FRANCISCO",
    },
    2: {
      formaEntrega: "3 dias ",
      formaPago: "Transferencia Bancaria",
      mantenimientoOferta: "Cta Cte. 60 dias F/Factura",
      nombreProveedor: "OLMOS CARLOS (DIOL)",
    },
    3: {
      formaEntrega: "Según pliego",
      formaPago: "Según pliego",
      mantenimientoOferta: "30 dias",
      nombreProveedor: "SERVICIOS HIGIENICOS DEL NOA",
    },
    4: {
      formaEntrega: "Según pliego",
      formaPago: "Según pliego",
      mantenimientoOferta: "Según pliego",
      nombreProveedor: "RODRIGUEZ BOSCHERO ESTEBAN",
    },
  },
};
